/*
 * Babel configuration.
 *
 * Hand-written rather than generated by `babel-preset-expo` because NativeWind
 * needs two hooks, and `create-expo-app` does not add either of them:
 *
 *   1. `jsxImportSource: 'nativewind'` makes the JSX runtime emit NativeWind's
 *      props wrapper, which is what turns a `className` into styled output.
 *   2. `nativewind/babel` collects those class names for the Metro CSS
 *      compiler. Order matters: the preset must come first so its JSX transform
 *      is already in place when NativeWind's plugin runs.
 *
 * `api.cache(true)` is required, not decorative. Metro caches this module in
 * memory and re-runs it per bundle; without a cache declaration it is
 * re-evaluated on every rebuild and file watching misses changes.
 */
module.exports = function babelConfig(api) {
  api.cache(true);

  return {
    presets: [['babel-preset-expo', { jsxImportSource: 'nativewind' }], 'nativewind/babel'],
  };
};
